server:
  port: 8082

spring:
  application:
    name: pricing-service

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:pricingdata

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    service-url:
      default-zone: http://localhost:8761/eureka/

instance:
  preferIpAddress: true

